### ISSUE TITLE
Add attribution at the beginning of htmltruncate.py

### ISSUE THREAD

**Issue by jterstriep** [eentzel/htmltruncate.py#4]
I really just wanted to say thanks. Your code save me hours.  But I would also suggest that you add some attributation information at the beginning of htmltruncate.py (the source file) as I just copied the file into
my project and I'd like to give credit where credit is due.

**Comment by eentzel** [comment]
Glad you found the code useful! Thanks for taking the time to say so & for the suggestion. Just added a license to all the .py files.
